development:
  adapter: postgresql
  encoding: unicode
  database: virtual_trainer_dev
  pool: 5
  username: postgres
  password:
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: virtual_trainer_test
  pool: 5
  username: postgres
  password:
  timeout: 5000

